-- Create the raw_videos table
CREATE OR REPLACE TABLE youtube_sentiment.raw_videos (
    ID STRING,
    TITLE STRING,
    DESCRIPTION STRING,
    PUBLISHED_AT STRING,
    CATEGORY_ID STRING,
    DURATION STRING,
    CAPTION STRING,
    LIKE_COUNT INT64,
    COMMENT_COUNT INT64,
    VIEW_COUNT INT64
);

-- Create the raw_comments table
CREATE OR REPLACE TABLE youtube_sentiment.raw_comments (
    REPLY_COUNT INT64,
    AUTHOR STRING,
    TEXT STRING,
    LIKE_COUNT INT64,
    PUBLISHED_AT STRING,
    VIDEO_ID STRING,
);

-- Create the videos table
CREATE OR REPLACE TABLE youtube_sentiment.videos (
    ID STRING,
    TITLE STRING,
    DESCRIPTION STRING,
    PUBLISHED_AT TIMESTAMP,
    CATEGORY_ID STRING,
    DURATION INT64,
    CAPTION BOOLEAN,
    LIKE_COUNT INT64,
    COMMENT_COUNT INT64,
    VIEW_COUNT INT64,
    AVERAGE_SCORE FLOAT64,
    MAX_SCORE FLOAT64,
    MIN_SCORE FLOAT64
);

-- Create the comments table
CREATE OR REPLACE TABLE youtube_sentiment.comments (
    ID SERIAL,
    VIDEO_ID STRING,
    REPLY_COUNT INT64,
    AUTHOR STRING,
    TEXT STRING,
    LIKE_COUNT INT64,
    PUBLISHED_AT TIMESTAMP,
    SCORE FLOAT64,
    FOREIGN KEY (VIDEO_ID) REFERENCES videos(ID)
);

-- Create the users table
CREATE OR REPLACE TABLE youtube_sentiment.users (
    AUTHOR STRING,
    COMMENT_COUNT INT64
);
